#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

apt-get -y update
apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" | tee /var/www/html/index.html
nginx -t
service nginx reload
